apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ instance_name }}-flasky-ci
  labels:
    app: {{ instance_name }}-flasky-ci
  annotations:
    io.daocloud.dcs/deploy: force
spec:
  hostAliases:
  - ip: "10.18.1.56"
    hostnames:
    - "registry.dx.io"
  selector:
    matchLabels:
      app: {{ instance_name }}-flasky-ci
  template:
    metadata:
      name: {{ instance_name }}-flasky-ci
      labels:
        app: {{ instance_name }}-flasky-ci
    spec:
      containers:
      - name: {{ instance_name }}-flasky-ci
        image: {{ flasky-ci.image }}
        ports:
        - containerPort: 5000 # 容器端口
        resources:
          limits:
            cpu: "1" # cpu 限制
            memory: "1000Mi" # 内存限制
          requests:
            cpu: "1" # cpu 预留（与限制值一致）
            memory: "1000Mi" # 内存预留（与限制值一致）

---
apiVersion: v1
kind: Service
metadata:
  name: {{ instance_name }}-flasky-ci
spec:
  type: NodePort
  ports:
  - port: 5000 # 服务端口
  selector:
    app: {{ instance_name }}-flasky-ci
